# Generated by Django 5.2.4 on 2025-11-13 01:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0003_remove_booking_payment_status_alter_booking_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gateway_type', models.CharField(choices=[('PAYPAL', 'Paypal'), ('AMARPAY', 'Amarpay'), ('SHURJOPAY', 'Shurjopay')], max_length=15)),
                ('gateway_transaction_id', models.CharField(max_length=255)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('PENDING', 'Payment_Pending'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='Unpaid', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='booking.booking')),
            ],
        ),
    ]
