# Generated by Django 5.2.4 on 2025-11-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway_transaction_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
