# Generated by Django 5.2.4 on 2025-12-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_gateway_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway_type',
            field=models.CharField(choices=[('PAYPAL', 'Paypal'), ('SSLCOMMERZ', 'Sslcommerz'), ('AMARPAY', 'Amarpay'), ('SHURJOPAY', 'Shurjopay')], max_length=15),
        ),
    ]
