# Generated by Django 5.2.4 on 2025-12-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_gateway_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway_transaction_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
