# Generated by Django 5.2.4 on 2025-12-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_alter_payment_gateway_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status_reason",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
