# Generated by Django 5.2.4 on 2026-01-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_payment_status_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("UNPAID", "Unpaid"),
                    ("PENDING", "Payment_Pending"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="UNPAID",
                max_length=16,
            ),
        ),
    ]
