# Generated by Django 5.2.4 on 2025-11-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_total_money'),
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ManyToManyField(related_name='seat_booking', to='theater.seat'),
        ),
    ]
