# Generated by Django 5.2.4 on 2026-01-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_remove_booking_payment_status_alter_booking_seat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="payment_id",
        ),
    ]
