# Generated by Django 5.2.3 on 2025-06-26 03:06

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("ACTION", "Action"),
                            ("ADVENTURE", "Adventure"),
                            ("ANIMATION", "Animation"),
                            ("COMEDY", "Comedy"),
                            ("CRIME", "Crime"),
                            ("DOCUMENTARY", "Documentary"),
                            ("DRAMA", "Drama"),
                            ("FANTASY", "Fantasy"),
                            ("HISTORICAL", "Historical"),
                            ("HORROR", "Horror"),
                            ("MUSICAL", "Musical"),
                            ("MYSTERY", "Mystery"),
                            ("ROMANCE", "Romance"),
                            ("SCIFI", "Sci-Fi"),
                            ("THRILLER", "Thriller"),
                            ("WAR", "War"),
                            ("WESTERN", "Western"),
                            ("FAMILY", "Family"),
                            ("BIOGRAPHY", "Biography"),
                            ("SPORTS", "Sports"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("BANGLA", "Bangla"),
                            ("ENGLISH", "English"),
                            ("HINDI", "Hindi"),
                        ],
                        max_length=15,
                    ),
                ),
                ("poster", models.ImageField(upload_to=movie.models.upload_to)),
                ("release_date", models.DateField()),
                ("actor", models.ManyToManyField(to="actor.actor_detail")),
            ],
        ),
    ]
